customhost = "employee.ctvfjmlxrote.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ryanwongyisyen-bucket"
customregion = "us-east-1"
